### ISSUE TITLE
svgHeight

### ISSUE THREAD

**Issue by QsROg8320** [scttcper/ngx-trend#200]
Thanks for your job. Can you make svgHeight like input property. I want to set svgHeight='100%' but I can't do it.

**Comment by QsROg8320** [comment]
Thanks, but, now it doesn't work, I think this part need to replace.

https://github.com/scttcper/ngx-trend/blob/51418cd7bbc8c530d89eba8af1a5468fb16326f5/src/lib/trend/trend.component.ts#L105
```
 @Input() svgHeight: string | number = null;
  @Input() svgWidth: string | number = null;
```
https://github.com/scttcper/ngx-trend/blob/51418cd7bbc8c530d89eba8af1a5468fb16326f5/src/lib/trend/trend.component.ts#L146

```
this.svgWidth =this.svgWidth==null?( this.width || '100%'):this.svgWidth;
this.svgHeight =this.svgHeight==null?( this.height || '25%'):this.svgHeight;
```

**Comment by scttcper** [comment]
Any string you pass in will be used instead. I think it’s probably string only not number
