### ISSUE TITLE
I get following error when i try to implement ngx-trend (basic example) from readme. 

### ISSUE THREAD

**Issue by kimhegg** [scttcper/ngx-trend#264]
Template error: Can't bind to 'ngIf' since it isn't a known property of 'svg'

**Comment by scttcper** [comment]
What version of angular and is ivy enabled

**Comment by kimhegg** [comment]
8.2.13 and ivy is enabled yes.

**Comment by scttcper** [comment]
Ivy won’t work until angular 9 with almost everything except basic examples

**Comment by kimhegg** [comment]
Ok good to know. Might add that on readme :) cheers!
