### ISSUE TITLE
gradient binding is not working

### ISSUE THREAD

**Issue by aguerot** [scttcper/ngx-trend#74]
# Setup
`"ngx-trend": "^3.0.4"`

I have this code in my component
`
<ngx-trend autoDraw="true" autoDrawDuration="1000" autoDrawEasing="ease-out" smooth="true"
            [data]="[7,5,3,1,0,0]" [gradient]="[ '#1feaea', '#ffd200', '#f72047' ]"
            strokeLinecap="round" >
</ngx-trend>
`

# Result
The gradient is not applied to the path thus trend line is invisible

# Expected result
Gradient is applied correctly

# Workaround
Remove `[gradient]` property from markup but the trendline is then black

# My guess
The generated stroke reference in path is not formatted correctly as per bellow:
`<path class="ng-tns-c25-26 ng-trigger ng-trigger-pathAnimaiton" fill="none" stroke="url('http://localhost:4300/#/dashboard#ngx-trend-vertical-gradient-4337036028564612" d="M 8,8
L 55.213284686572436,22.01199092810751
S 64.8,24.857142857142854 74.38671531342756,27.702294786178197
L 112.01328468657243,38.86913378525037
S 121.6,41.714285714285715 131.18671531342756,44.559437643321054
L 168.81328468657244,55.72627664239323
S 178.4,58.57142857142857 188.29168704874172,60.039259396065795
L 225.30831295125827,65.53216917536277
S 235.2,67 245.2,67
L 292,67" style=""></path>`

missing  **')** at the end of stroke atribute here:

`stroke="url('http://localhost:4300/#/dashboard#ngx-trend-vertical-gradient-4337036028564612"`

**Comment by scttcper** [comment]
it looks like you're using hash based routing and that's breaking it. I guess i should fix that. The missing bracket would also be nice.

**Comment by scttcper** [comment]
should be fixed in 3.1.0

**Comment by aguerot** [comment]
great, thanks for the heads up

**Comment by aguerot** [comment]
works like a charm, thanks!
